apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ew0KICAgICJhdXRocyI6IHsNCiAgICAgICAgICAgICJnaGNyLmlvIjogew0KICAgICAgICAgICAgICAgICAgICJhdXRoIjogIllYQm9aV3hsYjI0NloyaHdYM1ZMWWtKcVltaHJXbUl5U0hoamJtczFTMDVJTkdKMk5HNDVhbFpoT1RSTWQxWnBOZz09Ig0KICAgICAgICAgICAgfQ0KICAgIH0NCn0=
type: kubernetes.io/dockerconfigjson
